backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "contenido"
    label: "Contenido"
    files:
      - name: "inicio"
        label: "Página de Inicio"
        file: "content/inicio.json"
        fields:
          - label: "Título principal"
            name: "titulo"
            widget: "string"

          - label: "Descripción"
            name: "descripcion"
            widget: "text"
